# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: gh:xonsh/xontrib-template
email: no@no.no
enable_autoloading: false
enable_pre_commit_hooks: true
full_name: anki-code
github_username: anki-code
has_aliases: false
has_events: false
package_manager: setuptools
project_name: clp
project_package_name: clp
project_repo_name: xontrib-clp
project_short_description: Copy output to clipboard.
pure_py: true
py_module_name: xontrib_clp
version: 0.0.1

