# Changes here will be overwritten by Copier
_commit: v0.1.0
_src_path: gh:xonsh/xontrib-template
email: no@no.no
enable_autoloading: false
enable_pre_commit_hooks: true
full_name: anki-code
github_username: anki-code
has_aliases: false
has_events: false
package_manager: setuptools
project_name: jump-to-dir
project_package_name: jump_to_dir
project_repo_name: xontrib-jump-to-dir
project_short_description: Jump to the directory by name.
pure_py: true
py_module_name: xontrib_jump_to_dir
version: 0.0.1

